languase: generic

sudo : required

services:
  - docker

before_install:
  - docker build -t 2hwayoung/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true 2hwayoung/react-test-app npm run test

after_success:
  - docker build -t 2hwayoung/docker-frontend ./frontend
  - docker build -t 2hwayoung/docker-backend ./backend
  - docker build -t 2hwayoung/docker-nginx ./nginx
  
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push 2hwayoung/docker-frontend
  - docker push 2hwayoung/docker-backend
  - docker push 2hwayoung/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-eart-1"
  app: docker-fullstack-app
  env: "Dockerfullstackapp-env"
  bucket_name: elasticbeanstalk-us-east-1-355670014736
  bucket_path: "docker-fullstack-app"
  on:
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY